### ISSUE TITLE
1.17.3 Child Lock And Wifi Connection Status

### ISSUE THREAD

**Issue by Flash4777** [dahlb/ha_blueair#158] opened 2024-12-09 15:26 UTC
Some Issues I see with this version are that the sensor for child lock on 405 and sense+ states that it is on when it is off. Also on the sense+ Wi-Fi status says disconnected even though I can still control them without problems from HA. Not sure about filter life sensor because my filters are currently good.

**Comment by chrisdfw** [comment] 2024-12-09 23:07
680i has the same child lock issue

**Comment by rainwoodman** [comment] 2024-12-18 07:46
I tried to reproduce this on my AWS based device. (680i and 405 are most likely the non-AWS devices). The AWS based device child lock is an HA switch, and by accident it also shows up as a sensor. In any case I noticed for my device, the ChildLock sensor is severely lagged behind because of the polling frequency being 5 (or 10) minutes. If I first switch ChildLock, and restart home assistant, the childlock sensor does update to the expected value.

Could you confirm if the problem is not explained by this lag?

**Comment by dahlb** [comment] 2024-12-20 12:33
confirmed child lock and brightness were not working on non-aws devices, fixed in 1.17.11

**Closed by dahlb** 2024-12-20 12:33 UTC
