### ISSUE TITLE
Setup error, reporting wifi status problem, won't load any entities 

### ISSUE THREAD

**Issue by sheepster-9k** [dahlb/ha_blueair#63] opened 2024-01-02 20:50 UTC
Error below: 
`2024-01-02 15:46:16.961 ERROR (MainThread) [custom_components.ha_blueair.blueair_data_update_coordinator] 'wifi_status'
2024-01-02 15:46:16.962 DEBUG (MainThread) [custom_components.ha_blueair.blueair_data_update_coordinator] Finished fetching ha_blueair-Little Blue data in 0.102 seconds (success: False)
2024-01-02 15:46:27.356 DEBUG (MainThread) [custom_components.ha_blueair] async setup entry: <homeassistant.config_entries.ConfigEntry object at 0x7fd688128940>`

Integration returns an error and unfortunately nothing loads

**Comment by dahlb** [comment] 2024-01-03 10:40
can you enable debugging on the api too so we can see what you do get from the API?

`blueair_api: debug`

**Comment by dahlb** [comment] 2024-01-13 01:07
duplicate of #61

**Closed by dahlb** 2024-01-13 01:07 UTC
Labels: bug
